# Generated by Django 5.0.1 on 2024-03-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='pincode',
            field=models.CharField(default='123', max_length=10),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
